### ISSUE TITLE
Something wrong with most recent publish

### ISSUE THREAD

**Issue by maclockard** [nteract/mathjax#13]
I recently encountered the error that https://github.com/nteract/mathjax/commit/243e89dc4a1aa79cf9b3531ebe4c92a530301dbd fixed:

```
TypeError: Cannot read property 'appendChild' of null
  at setScriptText (/home/circleci/project/node_modules/@nteract/mathjax/lib/node.js:113:34)
  at typeset (/home/circleci/project/node_modules/@nteract/mathjax/lib/node.js:90:18)
  at apply (/home/circleci/project/node_modules/@nteract/mathjax/lib/node.js:44:31)
  at r (/home/circleci/project/node_modules/@sentry/browser/src/helpers.ts:87:17)
```
However, I'm currently on `4.0.14` which has this commit, so I would expect this bug to be fixed. When I look at the source in `node_modules/@nteract/mathjax/src/node.tsx` I see the appropriate `null` check:
```ts
  /**
   * Create a script
   * @param { String } text
   */
  setScriptText(text: string) {
    const inline = this.props.inline;
    const type = types[this.props.input];

    if (!this.script && this.nodeRef.current) {
      this.script = document.createElement("script");
      this.script.type = `math/${type}; ${inline ? "" : "mode=display"}`;
      this.nodeRef.current.appendChild(this.script);
    }

    if (!this.script) {
      return;
    }

    this.script.text = text;
  }
```

But if look at the compiled code in `node_modules/@nteract/mathjax/lib/node.js`, it does not have the `null` check:
```js
    /**
     * Create a script
     * @param { String } text
     */
    setScriptText(text) {
        const inline = this.props.inline;
        const type = types[this.props.input];
        if (!this.script) {
            this.script = document.createElement("script");
            this.script.type = `math/${type}; ${inline ? "" : "mode=display"}`;
            this.nodeRef.current.appendChild(this.script);
        }
        // It _should_ be defined at this point, we'll just return at this point now
        if (!this.script) {
            return;
        }
        this.script.text = text;
    }
```
Also, if I manually rebuild the package in my `node_modules`, the `null` check is present in the compiled code. It would appear as though something went wrong with the publish process and the package wasn't properly rebuilt before hand. Would you mind trying to republish the package so that this fix is available?

**Comment by captainsafia** [comment]
Try 4.0.15?

**Comment by maclockard** [comment]
@captainsafia that did the trick! thanks for that rapid response time, I really appreciate it!
